<template>
  <svg
    width="20"
    height="20"
    viewBox="0 0 20 20"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="0.5"
      y="0.5"
      width="15"
      height="15"
      rx="3.5"
      fill="black"
      stroke="white"
    />
    <rect
      x="4.5"
      y="4.5"
      width="15"
      height="15"
      rx="3.5"
      fill="black"
      stroke="white"
    />
  </svg>
</template>
